apiVersion: v1
entries:
  cert-manager-crds:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-10T01:07:20.867247485Z"
    description: Cert Manager CRDs
    digest: 29f6c9f973567859549eb6f6312e50b26fce00cdae008546b0ef10f9de566d8e
    name: cert-manager-crds
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/cert-manager-crds-0.0.1.tgz
    version: 0.0.1
  do-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-10T01:07:20.867523881Z"
    description: Digital Ocean PVCs
    digest: a4cdb78d9f00037d0a0bf3a80e22a9e55bc4ea57c112eb95643fb462f392d864
    name: do-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/do-pvcs-0.0.2.tgz
    version: 0.0.2
  gce-pvcs:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-10T01:07:20.867736477Z"
    description: GCE PVCs
    digest: ec62849520634a45c49b22489ee9431916c2b1ca1f3631d0297ae8e2f43e44dd
    name: gce-pvcs
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/gce-pvcs-0.0.2.tgz
    version: 0.0.2
  generic-application:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-17T20:32:18.112768988Z"
    description: A Helm chart for Kubernetes
    digest: 7192ae2342ad7749666eedb406a6639b110b74fab564cbe78633dccce02a5cca
    name: generic-application
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/generic-application-0.1.17.tgz
    version: 0.1.17
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-17T16:32:31.583665616Z"
    description: A Helm chart for Kubernetes
    digest: afb77bdcee0d56182357ee8256d07e04e67121a292e4407f280a3317df2c18f1
    name: generic-application
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/generic-application-0.1.16.tgz
    version: 0.1.16
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-10T17:59:27.464487271Z"
    description: A Helm chart for Kubernetes
    digest: 3f1a22e9cd1136ee7fa1176f421d7f9bbf01d8082b27e9a2c61954b1430e758c
    name: generic-application
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/generic-application-0.1.15.tgz
    version: 0.1.15
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-10T01:07:20.868411767Z"
    description: A Helm chart for Kubernetes
    digest: d3cb6bb4bc4306199273d0035cefec13d323fa23ef647c72a70e364d95d60608
    name: generic-application
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/generic-application-0.1.14.tgz
    version: 0.1.14
  letsencrypt-issuer:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-10T01:07:20.868638063Z"
    description: Letsencrypt
    digest: 49e163d186f8be3c6373e8b535d9cebdf033ec5d61a5b01996b5c4258f45c243
    name: letsencrypt-issuer
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/letsencrypt-issuer-0.0.2.tgz
    version: 0.0.2
  namespaces:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-10T01:07:20.868815461Z"
    description: Namespaces
    digest: 9c4497cff53f1e748a9463af180d2be7efe7ee5d96bf28b7d92152d42f475900
    name: namespaces
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/namespaces-0.0.1.tgz
    version: 0.0.1
  oauth2-proxy-with-ingress:
  - apiVersion: v2
    appVersion: 3.2.0
    created: "2020-09-10T01:07:20.87014704Z"
    dependencies:
    - name: oauth2-proxy
      repository: '@stable'
      version: 3.2.0
    description: A Helm chart for Kubernetes
    digest: e6ec9d173381ccc3fb0f5a7b39b97063531bcc2aa70ff732e07cbbb13722f7d7
    name: oauth2-proxy-with-ingress
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/oauth2-proxy-with-ingress-0.0.5.tgz
    version: 0.0.5
  prometheus-statsd-exporter:
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2020-09-10T01:07:20.871489919Z"
    description: A Helm chart for Kubernetes
    digest: 41d7a9cb167add387c06d405b45698f99fe73376c11af82e2a83b62f776c845a
    name: prometheus-statsd-exporter
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/prometheus-statsd-exporter-0.1.31.tgz
    version: 0.1.31
  secret-spreader:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-10T01:07:20.871742115Z"
    description: Spreads secrets to multiple namespaces
    digest: b9a3ed7359d2fa970c3e4a45d62681b4db204801c32a2e2623f068b9771fd5d3
    name: secret-spreader
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/secret-spreader-0.0.2.tgz
    version: 0.0.2
  services:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-10T01:07:20.871970712Z"
    description: Services
    digest: 105a57c4b967ec77a4923d9fc741ec61376b3874262255691f04f1bd1eec607f
    name: services
    type: application
    urls:
    - https://razvvan.github.io/manotaur-charts/charts/services-0.0.1.tgz
    version: 0.0.1
generated: "2020-09-17T20:32:18.111519887Z"
